import type { SupportedLocale } from "@/config/locales";

export type FundingStrings = {
  eyebrow: string; title: string; body: string; oneTime: string; monthly: string; annual: string;
  amount: string; customAmount: string; accept: string; start: string; processing: string; error: string;
  cancelled: string; noInfluence: string; provider: string; fees: string; withdrawal: string;
  bankTitle: string; bankBody: string; bankUnavailable: string; successTitle: string; successBody: string; home: string;
};

const EN: FundingStrings = {
  eyebrow: "Voluntary support", title: "Help VoiceOpenGov grow worldwide.", body: "Membership remains free. Choose a one-time or recurring contribution independently of membership.",
  oneTime: "One time", monthly: "Monthly", annual: "Annually", amount: "Amount", customAmount: "Custom amount in EUR", accept: "I understand that this is voluntary support and does not purchase voting weight, access or political influence.",
  start: "Continue securely with Stripe", processing: "Preparing secure checkout …", error: "Online checkout is temporarily unavailable. Please use bank transfer or try again later.", cancelled: "Checkout was cancelled. Nothing was charged.",
  noInfluence: "Money never buys a stronger political voice at VoiceOpenGov.", provider: "Payment is processed by Stripe. VoiceOpenGov does not receive card details.", fees: "Stripe may offer payment methods and show any applicable fees before confirmation.", withdrawal: "Cancellation, refund and withdrawal rights depend on the payment type and applicable law. The final notice is shown before payment.",
  bankTitle: "Bank transfer", bankBody: "Bank transfer remains available as an independent fallback.", bankUnavailable: "Bank details are available on request.", successTitle: "Thank you for supporting VoiceOpenGov.", successBody: "Stripe is processing the payment. A payment is only recorded after provider confirmation.", home: "Back to VoiceOpenGov",
};

export const FUNDING_STRINGS: Record<SupportedLocale, FundingStrings> = {
  en: EN,
  de: { ...EN, eyebrow: "Freiwillige Unterstützung", title: "Hilf VoiceOpenGov, weltweit zu wachsen.", body: "Die Mitgliedschaft bleibt kostenfrei. Wähle unabhängig davon eine einmalige oder regelmäßige Unterstützung.", oneTime: "Einmalig", monthly: "Monatlich", annual: "Jährlich", amount: "Betrag", customAmount: "Eigener Betrag in EUR", accept: "Ich verstehe, dass dies eine freiwillige Unterstützung ist und weder Stimmgewicht noch Zugang oder politischen Einfluss kauft.", start: "Sicher mit Stripe fortfahren", processing: "Sicherer Checkout wird vorbereitet …", error: "Der Online-Checkout ist vorübergehend nicht verfügbar. Bitte nutze die Banküberweisung oder versuche es später erneut.", cancelled: "Der Checkout wurde abgebrochen. Es wurde nichts belastet.", noInfluence: "Geld kauft bei VoiceOpenGov niemals eine stärkere politische Stimme.", provider: "Die Zahlung wird durch Stripe verarbeitet. VoiceOpenGov erhält keine Kartendaten.", fees: "Stripe zeigt verfügbare Zahlungsarten und mögliche Gebühren vor der Bestätigung an.", withdrawal: "Storno-, Erstattungs- und Widerrufsrechte richten sich nach Zahlungsart und anwendbarem Recht. Der abschließende Hinweis erscheint vor der Zahlung.", bankTitle: "Banküberweisung", bankBody: "Die Banküberweisung bleibt als unabhängige Alternative verfügbar.", bankUnavailable: "Bankdaten erhältst du auf Anfrage.", successTitle: "Danke für deine Unterstützung.", successBody: "Stripe verarbeitet die Zahlung. Sie wird erst nach Bestätigung des Zahlungsanbieters verbucht.", home: "Zurück zu VoiceOpenGov" },
  fr: { ...EN, eyebrow: "Soutien volontaire", title: "Aidez VoiceOpenGov à se développer dans le monde.", body: "L’adhésion reste gratuite. Choisissez indépendamment un soutien unique ou régulier.", oneTime: "Unique", monthly: "Mensuel", annual: "Annuel", amount: "Montant", customAmount: "Montant libre en EUR", accept: "Je comprends que ce soutien volontaire n’achète aucun poids de vote, accès ou influence politique.", start: "Continuer en sécurité avec Stripe", processing: "Préparation du paiement sécurisé…", error: "Le paiement en ligne est temporairement indisponible. Utilisez le virement bancaire ou réessayez plus tard.", cancelled: "Le paiement a été annulé. Aucun débit.", noInfluence: "L’argent n’achète jamais une voix politique plus forte.", provider: "Le paiement est traité par Stripe. VoiceOpenGov ne reçoit aucune donnée de carte.", fees: "Stripe affiche les moyens de paiement disponibles et les éventuels frais avant la confirmation.", withdrawal: "Les droits d’annulation, de remboursement et de rétractation dépendent du moyen de paiement et du droit applicable. L’avis final apparaît avant le paiement.", bankTitle: "Virement bancaire", bankBody: "Le virement bancaire reste disponible comme solution indépendante.", bankUnavailable: "Les coordonnées bancaires sont disponibles sur demande.", successTitle: "Merci pour votre soutien.", successBody: "Stripe traite le paiement. Il n’est enregistré qu’après confirmation du prestataire.", home: "Retour à VoiceOpenGov" },
  es: { ...EN, eyebrow: "Apoyo voluntario", title: "Ayuda a VoiceOpenGov a crecer en todo el mundo.", body: "La membresía sigue siendo gratuita. Elige de forma independiente una aportación única o periódica.", oneTime: "Una vez", monthly: "Mensual", annual: "Anual", amount: "Importe", customAmount: "Importe libre en EUR", accept: "Entiendo que este apoyo voluntario no compra peso de voto, acceso ni influencia política.", start: "Continuar de forma segura con Stripe", processing: "Preparando el pago seguro…", error: "El pago en línea no está disponible temporalmente. Usa transferencia bancaria o inténtalo más tarde.", cancelled: "El pago se canceló. No se realizó ningún cargo.", noInfluence: "El dinero nunca compra una voz política más fuerte.", provider: "Stripe procesa el pago. VoiceOpenGov no recibe los datos de la tarjeta.", fees: "Stripe muestra los métodos de pago disponibles y las posibles comisiones antes de confirmar.", withdrawal: "Los derechos de cancelación, reembolso y desistimiento dependen del tipo de pago y la legislación aplicable. El aviso final se muestra antes de pagar.", bankTitle: "Transferencia bancaria", bankBody: "La transferencia bancaria sigue disponible como alternativa independiente.", bankUnavailable: "Los datos bancarios están disponibles previa solicitud.", successTitle: "Gracias por tu apoyo.", successBody: "Stripe está procesando el pago. Solo se registra tras la confirmación del proveedor.", home: "Volver a VoiceOpenGov" },
  tr: { ...EN, eyebrow: "Gönüllü destek", title: "VoiceOpenGov’un dünya çapında büyümesine yardım edin.", body: "Üyelik ücretsiz kalır. Bağımsız olarak tek seferlik veya düzenli destek seçin.", oneTime: "Tek sefer", monthly: "Aylık", annual: "Yıllık", amount: "Tutar", customAmount: "EUR olarak özel tutar", accept: "Bu gönüllü desteğin oy ağırlığı, erişim veya siyasi etki satın almadığını anlıyorum.", start: "Stripe ile güvenli devam et", processing: "Güvenli ödeme hazırlanıyor…", error: "Çevrimiçi ödeme geçici olarak kullanılamıyor. Banka havalesini kullanın veya daha sonra tekrar deneyin.", cancelled: "Ödeme iptal edildi. Ücret alınmadı.", noInfluence: "Para asla daha güçlü bir siyasi ses satın almaz.", provider: "Ödeme Stripe tarafından işlenir. VoiceOpenGov kart bilgilerini almaz.", fees: "Stripe, onaydan önce kullanılabilir ödeme yöntemlerini ve varsa ücretleri gösterir.", withdrawal: "İptal, iade ve cayma hakları ödeme türüne ve geçerli hukuka bağlıdır. Son bilgilendirme ödemeden önce gösterilir.", bankTitle: "Banka havalesi", bankBody: "Banka havalesi bağımsız bir alternatif olarak kullanılabilir.", bankUnavailable: "Banka bilgileri talep üzerine sağlanır.", successTitle: "Desteğiniz için teşekkürler.", successBody: "Stripe ödemeyi işliyor. Ödeme yalnızca sağlayıcı onayından sonra kaydedilir.", home: "VoiceOpenGov’a dön" },
  ar: { ...EN, eyebrow: "دعم طوعي", title: "ساعد VoiceOpenGov على النمو عالميًا.", body: "تظل العضوية مجانية. اختر دعمًا لمرة واحدة أو دعمًا دوريًا بشكل مستقل.", oneTime: "مرة واحدة", monthly: "شهريًا", annual: "سنويًا", amount: "المبلغ", customAmount: "مبلغ مخصص باليورو", accept: "أفهم أن هذا دعم طوعي ولا يشتري وزنًا تصويتيًا أو وصولًا أو نفوذًا سياسيًا.", start: "المتابعة بأمان مع Stripe", processing: "جارٍ تجهيز الدفع الآمن…", error: "الدفع الإلكتروني غير متاح مؤقتًا. استخدم التحويل البنكي أو حاول لاحقًا.", cancelled: "تم إلغاء الدفع ولم يتم الخصم.", noInfluence: "المال لا يشتري أبدًا صوتًا سياسيًا أقوى.", provider: "تُعالج Stripe الدفع، ولا تتلقى VoiceOpenGov بيانات البطاقة.", fees: "تعرض Stripe وسائل الدفع المتاحة وأي رسوم مطبقة قبل التأكيد.", withdrawal: "تعتمد حقوق الإلغاء والاسترداد والانسحاب على نوع الدفع والقانون المعمول به. يظهر الإشعار النهائي قبل الدفع.", bankTitle: "تحويل بنكي", bankBody: "يبقى التحويل البنكي متاحًا كبديل مستقل.", bankUnavailable: "البيانات البنكية متاحة عند الطلب.", successTitle: "شكرًا لدعمك.", successBody: "تُعالج Stripe الدفعة، ولا تُسجل إلا بعد تأكيد مزود الدفع.", home: "العودة إلى VoiceOpenGov" },
  pl: { ...EN, eyebrow: "Dobrowolne wsparcie", title: "Pomóż VoiceOpenGov rozwijać się na całym świecie.", body: "Członkostwo pozostaje bezpłatne. Niezależnie od niego wybierz wsparcie jednorazowe lub cykliczne.", oneTime: "Jednorazowo", monthly: "Miesięcznie", annual: "Rocznie", amount: "Kwota", customAmount: "Własna kwota w EUR", accept: "Rozumiem, że wsparcie nie kupuje siły głosu, dostępu ani wpływu politycznego.", start: "Przejdź bezpiecznie do Stripe", processing: "Przygotowywanie płatności…", error: "Płatność online jest chwilowo niedostępna. Użyj przelewu lub spróbuj później.", cancelled: "Płatność anulowano. Nie pobrano żadnej kwoty.", noInfluence: "Pieniądze nigdy nie kupują silniejszego głosu politycznego.", provider: "Płatność obsługuje Stripe. VoiceOpenGov nie otrzymuje danych karty.", fees: "Stripe pokaże dostępne metody płatności i ewentualne opłaty przed potwierdzeniem.", withdrawal: "Prawo do anulowania, zwrotu i odstąpienia zależy od typu płatności i właściwego prawa. Ostateczna informacja pojawia się przed płatnością.", bankTitle: "Przelew bankowy", bankBody: "Przelew bankowy pozostaje niezależną alternatywą.", bankUnavailable: "Dane do przelewu są dostępne na życzenie.", successTitle: "Dziękujemy za wsparcie.", successBody: "Stripe przetwarza płatność. Zostanie ona zapisana dopiero po potwierdzeniu przez operatora.", home: "Powrót do VoiceOpenGov" },
  it: { ...EN, eyebrow: "Sostegno volontario", title: "Aiuta VoiceOpenGov a crescere nel mondo.", body: "L’adesione resta gratuita. Scegli indipendentemente un contributo unico o ricorrente.", oneTime: "Una volta", monthly: "Mensile", annual: "Annuale", amount: "Importo", customAmount: "Importo libero in EUR", accept: "Comprendo che il sostegno non acquista peso di voto, accesso o influenza politica.", start: "Continua in sicurezza con Stripe", processing: "Preparazione del pagamento…", error: "Il pagamento online è temporaneamente non disponibile. Usa il bonifico o riprova più tardi.", cancelled: "Il pagamento è stato annullato. Non è stato addebitato nulla.", noInfluence: "Il denaro non compra mai una voce politica più forte.", provider: "Il pagamento è elaborato da Stripe. VoiceOpenGov non riceve i dati della carta.", fees: "Stripe mostra i metodi di pagamento disponibili e le eventuali commissioni prima della conferma.", withdrawal: "I diritti di annullamento, rimborso e recesso dipendono dal tipo di pagamento e dalla legge applicabile. L’avviso finale appare prima del pagamento.", bankTitle: "Bonifico bancario", bankBody: "Il bonifico bancario resta disponibile come alternativa indipendente.", bankUnavailable: "Le coordinate bancarie sono disponibili su richiesta.", successTitle: "Grazie per il sostegno.", successBody: "Stripe sta elaborando il pagamento. Sarà registrato solo dopo la conferma del fornitore.", home: "Torna a VoiceOpenGov" },
  ru: { ...EN, eyebrow: "Добровольная поддержка", title: "Помогите VoiceOpenGov развиваться по всему миру.", body: "Членство остаётся бесплатным. Независимо от него выберите разовую или регулярную поддержку.", oneTime: "Один раз", monthly: "Ежемесячно", annual: "Ежегодно", amount: "Сумма", customAmount: "Своя сумма в EUR", accept: "Я понимаю, что поддержка не покупает вес голоса, доступ или политическое влияние.", start: "Безопасно продолжить через Stripe", processing: "Подготовка безопасной оплаты…", error: "Онлайн-оплата временно недоступна. Используйте банковский перевод или повторите позже.", cancelled: "Оплата отменена. Средства не списаны.", noInfluence: "Деньги никогда не покупают более сильный политический голос.", provider: "Платёж обрабатывает Stripe. VoiceOpenGov не получает данные карты.", fees: "Stripe покажет доступные способы оплаты и возможные комиссии до подтверждения.", withdrawal: "Права на отмену, возврат и отказ зависят от типа платежа и применимого права. Итоговое уведомление показывается до оплаты.", bankTitle: "Банковский перевод", bankBody: "Банковский перевод остаётся независимой альтернативой.", bankUnavailable: "Банковские реквизиты предоставляются по запросу.", successTitle: "Спасибо за поддержку.", successBody: "Stripe обрабатывает платёж. Он будет учтён только после подтверждения провайдера.", home: "Вернуться в VoiceOpenGov" },
  zh: { ...EN, eyebrow: "自愿支持", title: "帮助 VoiceOpenGov 在全球发展。", body: "会员资格始终免费。您可以独立选择一次性或定期支持。", oneTime: "一次性", monthly: "每月", annual: "每年", amount: "金额", customAmount: "自定义欧元金额", accept: "我明白，自愿支持不会购买投票权重、访问权限或政治影响力。", start: "通过 Stripe 安全继续", processing: "正在准备安全结账…", error: "在线结账暂时不可用。请使用银行转账或稍后重试。", cancelled: "结账已取消，未收取任何费用。", noInfluence: "金钱永远不能购买更强的政治话语权。", provider: "付款由 Stripe 处理。VoiceOpenGov 不会收到银行卡信息。", fees: "Stripe 会在确认前显示可用的付款方式及任何适用费用。", withdrawal: "取消、退款和撤回权取决于付款类型和适用法律。付款前会显示最终说明。", bankTitle: "银行转账", bankBody: "银行转账仍可作为独立的备用方式。", bankUnavailable: "银行账户信息可按需提供。", successTitle: "感谢您的支持。", successBody: "Stripe 正在处理付款。只有在支付服务商确认后才会记录该付款。", home: "返回 VoiceOpenGov" },
};
